[tool.black]
line-length = 120
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.buildout
    | bin
    | etc
    | venv
    | scripts
    | stresstests
    | uninstall_addons
  )/
  | bootstrap.py
)
'''
