# -*- coding: utf-8 -*-
"""
This script sanitizes a copy of a production database
so it becomes safe to use in a test environment.

Run this script with bin/python_odoo as generated by buildout.

NEVER RUN THIS SCRIPT ON THE PRODUCTION DATABASE.
"""
import argparse
import psycopg2
from contextlib import closing
from odoo import api


parser = argparse.ArgumentParser(description="Update the database to set it safe for testing")
parser.add_argument('database')
args = parser.parse_args()


session.open(db=args.database)
with api.Environment.manage():
    env = api.Environment(session.cr, 1, {})
    # disable outgoing mail servers
    env.cr.execute("UPDATE ir_mail_server SET smtp_host=smtp_host || '.disabled', active=FALSE")
    # disable incomming mail servers
    env.cr.execute("UPDATE fetchmail_server SET server=server || '.disabled', active=FALSE, state='draft'")
    ## remove google analytics key
    # env.cr.execute("UPDATE website SET google_analytics_key=NULL")

    module = env['ir.module.module'].search([('name', 'like', 'website_no_crawler')])
    if module:
        module.button_immediate_install()

    module = env['ir.module.module'].search([('name', 'like', 'website_environment_ribbon')])
    if module:
        module.button_immediate_install()

    env.cr.commit()

print("done")
